# Generated by Django 3.0.3 on 2020-04-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userName',
            field=models.CharField(blank=True, max_length=128, verbose_name='userName'),
        ),
    ]
